/*
 * Polaczony.java
 *
 * Created on 12 stycze  2008, 17:36
 */

package swing;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jmuserver.gs.ClientThread;
import tools.HexLinePackage;
import tools.WrongCharacter;

/**
 *
 * @author  Miki
 */
public class Polaczony extends javax.swing.JPanel {
    private ClientThread _client;
    /** Creates new form Polaczony */
    public Polaczony(ClientThread c) {
        _client=c;
        initComponents();
        
    }

    public void addLog(String string) {
       jTextLogArea.append(string+"\n");
    }
    public void addPac(String s)
    {
        jTextPrzychodzaceArea.append(s+"\n");
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPrzychodzaceArea = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextLogArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        LiniaDolna = new javax.swing.JEditorPane();

        jTextPrzychodzaceArea.setColumns(20);
        jTextPrzychodzaceArea.setEditable(false);
        jTextPrzychodzaceArea.setRows(5);
        jTextPrzychodzaceArea.setBorder(javax.swing.BorderFactory.createTitledBorder("Przychodzace"));
        jScrollPane1.setViewportView(jTextPrzychodzaceArea);

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Wyslij");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextLogArea.setColumns(20);
        jTextLogArea.setRows(5);
        jTextLogArea.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Logi"));
        jScrollPane2.setViewportView(jTextLogArea);

        LiniaDolna.setEditable(false);
        jScrollPane3.setViewportView(LiniaDolna);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, 0, 0, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addComponent(jTextField1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
ParseLine(jTextField1.getText());
    }//GEN-LAST:event_jTextField1ActionPerformed
    private void ParseLine(String s)
    {
        try {
            HexLinePackage t = new HexLinePackage(s);
            byte[] pac = t.getContent();
            _client.getConnection().sendPacket(pac);
            jTextField1.setText("");
            LiniaDolna.setText("Paczk : " + s +" Pomyslne wyslana");
        } catch (IOException ex) {
            Logger.getLogger(Polaczony.class.getName()).log(Level.SEVERE, null, ex);
        } catch (WrongCharacter ex) {
           jTextField1.setText("");
           LiniaDolna.setText("zly znak "+ex.getCharacter());
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane LiniaDolna;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JTextArea jTextLogArea;
    public javax.swing.JTextArea jTextPrzychodzaceArea;
    // End of variables declaration//GEN-END:variables
    
}
